apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: alpine
    command: ["sleep", "3500"]
    volumeMounts: 
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: abhi-secret # no -

# kubectl exce -it myapp -- /bin/sh
# cat /etc/secrets/username



