# secret-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: my-container
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - secretRef:
        name: my-secret




        or

 #each each value using env variable

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: my-container
    image: alpine
    command: ["sleep", "3600"]
    env:
    - name: password
      valueFrom:
      secretKeyRef:
        name: (name of secret)
        key: password
